// <auto-generated />
using System;
using System.Collections.Generic;
using MAS_Implementation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MAS_Implementation.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.27");

            modelBuilder.Entity("MAS_Implementation.Models.Auction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AuctioneerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Facility")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ReservePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuctioneerId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Auctions");
                });

            modelBuilder.Entity("MAS_Implementation.Models.AuctionRound", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuctionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.ToTable("AuctionRounds");
                });

            modelBuilder.Entity("MAS_Implementation.Models.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<int>("AuctionRoundId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BidderId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAbsentee")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MaxAmount")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuctionRoundId");

                    b.HasIndex("BidderId");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("MAS_Implementation.Models.Bidder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("PermanentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RegistrarId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tier")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PermanentId")
                        .IsUnique();

                    b.HasIndex("RegistrarId");

                    b.ToTable("Bidders");
                });

            modelBuilder.Entity("MAS_Implementation.Models.ConsignmentAgreement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CommissionRate")
                        .HasColumnType("REAL");

                    b.Property<int>("ConsignorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConsignorId");

                    b.ToTable("ConsignmentAgreements");
                });

            modelBuilder.Entity("MAS_Implementation.Models.Consignor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CataloguerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CataloguerId");

                    b.ToTable("Consignors");
                });

            modelBuilder.Entity("MAS_Implementation.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IssuingAuthority")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VerificationTaskId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VerificationTaskId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("MAS_Implementation.Models.Lot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AuctionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AuctionRoundId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CataloguerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ConsignmentAgreementId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryOfOrigin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<double>("EstimateHigh")
                        .HasColumnType("REAL");

                    b.Property<double>("EstimateLow")
                        .HasColumnType("REAL");

                    b.Property<double>("ReservePrice")
                        .HasColumnType("REAL");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.HasIndex("AuctionRoundId");

                    b.HasIndex("CataloguerId");

                    b.HasIndex("ConsignmentAgreementId");

                    b.ToTable("Lots");
                });

            modelBuilder.Entity("MAS_Implementation.Models.Paddle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuctionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BidderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaddleNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BidderId");

                    b.HasIndex("PaddleNumber")
                        .IsUnique();

                    b.HasIndex("AuctionId", "PaddleNumber")
                        .IsUnique();

                    b.ToTable("Paddles");
                });

            modelBuilder.Entity("MAS_Implementation.Models.StaffMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.ComplexProperty<Dictionary<string, object>>("ContactInformation", "MAS_Implementation.Models.StaffMember.ContactInformation#ContactInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Address")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasColumnType("TEXT");
                        });

                    b.HasKey("Id");

                    b.ToTable("StaffMembers");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("MAS_Implementation.Models.VerificationTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomCleranceNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("LotId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LotId");

                    b.ToTable("VerificationTasks");
                });

            modelBuilder.Entity("MAS_Implementation.Models.Auctioneer", b =>
                {
                    b.HasBaseType("MAS_Implementation.Models.StaffMember");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.ToTable("Auctioneers");
                });

            modelBuilder.Entity("MAS_Implementation.Models.Cataloguer", b =>
                {
                    b.HasBaseType("MAS_Implementation.Models.StaffMember");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.ToTable("Cataloguers");
                });

            modelBuilder.Entity("MAS_Implementation.Models.Manager", b =>
                {
                    b.HasBaseType("MAS_Implementation.Models.StaffMember");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("MAS_Implementation.Models.Registrar", b =>
                {
                    b.HasBaseType("MAS_Implementation.Models.StaffMember");

                    b.ToTable("Registrars");
                });

            modelBuilder.Entity("MAS_Implementation.Models.Auction", b =>
                {
                    b.HasOne("MAS_Implementation.Models.Auctioneer", "Auctioneer")
                        .WithMany("Auctions")
                        .HasForeignKey("AuctioneerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MAS_Implementation.Models.Manager", "Manager")
                        .WithMany("Auctions")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Auctioneer");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("MAS_Implementation.Models.AuctionRound", b =>
                {
                    b.HasOne("MAS_Implementation.Models.Auction", "Auction")
                        .WithMany("Rounds")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");
                });

            modelBuilder.Entity("MAS_Implementation.Models.Bid", b =>
                {
                    b.HasOne("MAS_Implementation.Models.AuctionRound", "AuctionRound")
                        .WithMany("Bids")
                        .HasForeignKey("AuctionRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MAS_Implementation.Models.Bidder", "Bidder")
                        .WithMany("Bids")
                        .HasForeignKey("BidderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuctionRound");

                    b.Navigation("Bidder");
                });

            modelBuilder.Entity("MAS_Implementation.Models.Bidder", b =>
                {
                    b.HasOne("MAS_Implementation.Models.Registrar", "Registrar")
                        .WithMany("Bidders")
                        .HasForeignKey("RegistrarId");

                    b.Navigation("Registrar");
                });

            modelBuilder.Entity("MAS_Implementation.Models.ConsignmentAgreement", b =>
                {
                    b.HasOne("MAS_Implementation.Models.Consignor", "Consignor")
                        .WithMany("ConsignmentAgreements")
                        .HasForeignKey("ConsignorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Consignor");
                });

            modelBuilder.Entity("MAS_Implementation.Models.Consignor", b =>
                {
                    b.HasOne("MAS_Implementation.Models.Cataloguer", "Cataloguer")
                        .WithMany("Consignors")
                        .HasForeignKey("CataloguerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cataloguer");
                });

            modelBuilder.Entity("MAS_Implementation.Models.Document", b =>
                {
                    b.HasOne("MAS_Implementation.Models.VerificationTask", null)
                        .WithMany("Documents")
                        .HasForeignKey("VerificationTaskId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MAS_Implementation.Models.Lot", b =>
                {
                    b.HasOne("MAS_Implementation.Models.Auction", "Auction")
                        .WithMany("Lots")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MAS_Implementation.Models.AuctionRound", null)
                        .WithMany("Lots")
                        .HasForeignKey("AuctionRoundId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MAS_Implementation.Models.Cataloguer", "Cataloguer")
                        .WithMany("Lots")
                        .HasForeignKey("CataloguerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MAS_Implementation.Models.ConsignmentAgreement", "ConsignmentAgreement")
                        .WithMany("Lots")
                        .HasForeignKey("ConsignmentAgreementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("Cataloguer");

                    b.Navigation("ConsignmentAgreement");
                });

            modelBuilder.Entity("MAS_Implementation.Models.Paddle", b =>
                {
                    b.HasOne("MAS_Implementation.Models.Auction", "Auction")
                        .WithMany("Paddles")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MAS_Implementation.Models.Bidder", "Bidder")
                        .WithMany("Paddles")
                        .HasForeignKey("BidderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("Bidder");
                });

            modelBuilder.Entity("MAS_Implementation.Models.VerificationTask", b =>
                {
                    b.HasOne("MAS_Implementation.Models.Lot", "Lot")
                        .WithMany("VerificationTasks")
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lot");
                });

            modelBuilder.Entity("MAS_Implementation.Models.Auctioneer", b =>
                {
                    b.HasOne("MAS_Implementation.Models.StaffMember", null)
                        .WithOne()
                        .HasForeignKey("MAS_Implementation.Models.Auctioneer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MAS_Implementation.Models.Cataloguer", b =>
                {
                    b.HasOne("MAS_Implementation.Models.StaffMember", null)
                        .WithOne()
                        .HasForeignKey("MAS_Implementation.Models.Cataloguer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MAS_Implementation.Models.Manager", b =>
                {
                    b.HasOne("MAS_Implementation.Models.StaffMember", null)
                        .WithOne()
                        .HasForeignKey("MAS_Implementation.Models.Manager", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MAS_Implementation.Models.Registrar", b =>
                {
                    b.HasOne("MAS_Implementation.Models.StaffMember", null)
                        .WithOne()
                        .HasForeignKey("MAS_Implementation.Models.Registrar", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MAS_Implementation.Models.Auction", b =>
                {
                    b.Navigation("Lots");

                    b.Navigation("Paddles");

                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("MAS_Implementation.Models.AuctionRound", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("Lots");
                });

            modelBuilder.Entity("MAS_Implementation.Models.Bidder", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("Paddles");
                });

            modelBuilder.Entity("MAS_Implementation.Models.ConsignmentAgreement", b =>
                {
                    b.Navigation("Lots");
                });

            modelBuilder.Entity("MAS_Implementation.Models.Consignor", b =>
                {
                    b.Navigation("ConsignmentAgreements");
                });

            modelBuilder.Entity("MAS_Implementation.Models.Lot", b =>
                {
                    b.Navigation("VerificationTasks");
                });

            modelBuilder.Entity("MAS_Implementation.Models.VerificationTask", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("MAS_Implementation.Models.Auctioneer", b =>
                {
                    b.Navigation("Auctions");
                });

            modelBuilder.Entity("MAS_Implementation.Models.Cataloguer", b =>
                {
                    b.Navigation("Consignors");

                    b.Navigation("Lots");
                });

            modelBuilder.Entity("MAS_Implementation.Models.Manager", b =>
                {
                    b.Navigation("Auctions");
                });

            modelBuilder.Entity("MAS_Implementation.Models.Registrar", b =>
                {
                    b.Navigation("Bidders");
                });
#pragma warning restore 612, 618
        }
    }
}
